version: '3'

services: 
  # Database
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3306:3306
    # restart: always
    environment:
      MYSQL_ROOT_PASSWORD: xesApps
      MYSQL_DATABASE: xesAppsDb
      MYSQL_USER: xesApps
      MYSQL_PASSWORD: xesApps
    networks:
      - wpsite
  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    # restart: unless-stopped
    ports:
      - '8091:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: esApps 
    networks:
      - wpsite
  # Spring-Boot-JSF 
  jsf_boot:
    depends_on:
      - db
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - '8081:8081'
    restart: on-failure
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=xesApps
      - DATABASE_PASSWORD=xesApps
      - DATABASE_NAME=xesAppsDb
      - DATABASE_PORT=3306
     #WAIT_HOSTS: db:3306
    networks: 
      - wpsite
      
networks:
  wpsite:
volumes:
  db_data: